# Generated by Django 5.2.2 on 2025-06-07 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointBalance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.PositiveBigIntegerField(unique=True)),
                ('balance', models.DecimalField(decimal_places=10, default=0, max_digits=19)),
                ('version', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'db_table': 'point_balances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.PositiveBigIntegerField()),
                ('amount', models.PositiveBigIntegerField()),
                ('type', models.CharField(choices=[('EARN', 'EARN'), ('USED', 'USED'), ('CANCELED', 'CANCELED')], max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('balance_snapshot', models.PositiveBigIntegerField()),
                ('version', models.PositiveBigIntegerField(default=0)),
                ('point_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.pointbalance')),
            ],
            options={
                'db_table': 'points',
                'ordering': ['-created_at'],
            },
        ),
    ]
