version: "3"

services:
  points_db:
    image: mysql:8.0.40-debian
    platform: linux/amd64
    ports:
      - "23306:3306"
    expose:
      - "23306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: points_db
    volumes:
      - "./sqls/:/docker-entrypoint-initdb.d/"
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci

  points_cache:
    container_name: dev_django_points_cache
    image: redis:7.2-alpine
    ports:
      - "26379:6379"
    restart: unless-stopped